const JOB_STATUS = {
  DRAFT: "DRAFT",
  OPEN: "OPEN",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

const PROPOSAL_STATUS = {
  PENDING: "pending",
  ACCEPTED: "accepted",
  REJECTED: "rejected",
  WITHDRAWN: "withdrawn",
};

const CANCELLATION_STATUS = {
  NONE: "NONE",
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
};

const MILESTONE_STATUS = {
  ACTIVE: "ACTIVE",
  SUBMITTED: "SUBMITTED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

module.exports = {
  JOB_STATUS,
  PROPOSAL_STATUS,
  CANCELLATION_STATUS,
  MILESTONE_STATUS,
};
